cask_args appdir: "/Applications"

# tap "homebrew/cask"
tap "homebrew/bundle"
tap "nodenv/nodenv" 

brew "coreutils"
brew "ddate"
brew "editorconfig"
# brew "imagemagick"
# brew "openssl"
brew "watchman"
brew "readline"
brew "postgresql"
brew "rbenv"
brew "nodenv"
brew "nodenv-nvmrc"
brew "pyenv"
brew "wget"
brew "leiningen"
brew "tmux"
brew "gh"

cask "firefox"
cask "fluid"
