source ~/.profile
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle :compinstall filename '/Users/simon.dell/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=3000
SAVEHIST=3000
bindkey -v
# End of lines configured by zsh-newuser-install

# Grunt completion
# - I should probably have a completions list, or dotfile
eval "$(grunt --completion=zsh)"

# PROMPTS
export PROMPT=$'\n'"%2/"$'\n'"%_ > " # $pwd plus three levels up, new line, mode
export RPROMPT="%D %*" # yy-mm-dd 24:mm:ss
